### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by 04c1e0** [ChengF3ng233/Untitled#5]
二维码无法加载报错，如何解决
![73aa5876-b4ca-43ae-8b42-f0446f66ef64](https://github.com/user-attachments/assets/91992755-ca83-432d-a2eb-19ec7efb6cce)

**Comment by Stars-Azusa** [comment]
你怎么还能构建，我这里缺少cn.feng.untitled.music.api.base

**Comment by ChengF3ng233** [comment]
原来使用的api是别人搭建的，要挂梯子才能访问

**Comment by ChengF3ng233** [comment]
> 你怎么还能构建，我这里缺少cn.feng.untitled.music.api.base

看README.MD
